### PR TITLE
Arrays

### PR DESCRIPTION
**Pull request by Dragonink**
I implemented `ToBorrowed`, `ToOwned` and `IntoOwned` for `[T; N]`.

### CODE REVIEW

**Comment by alexkazik** [comment]
First of all thanks for the contribution.
But unfortunately your code is not compatible with the current msrv.
Do you think we should raise the msrv or change the code to work also with 1.58.1?
Also can you please move the array implementation above the tuples?

**Comment by Dragonink** [comment]
> But unfortunately your code is not compatible with the current msrv.

I implemented these traits because I need them in a project where I use the latest stable.
I forgot to check your MSRV beforehand, sorry.

> Do you think we should raise the msrv or change the code to work also with 1.58.1?

`core::array::from_fn` has been stabilized in 1.63, released in August 2022.
An alternative without raising MSRV would be to collect an iterator and use the array TryFrom implementation, something like:
```rust
self.iter()
    .map(ToOwned::to_owned)
    .collect::<Vec<_>>()
    .try_into()
    .unwrap()
```
Whatever you prefer.

> Also can you please move the array implementation above the tuples?

I can do that.

**Comment by alexkazik** [comment]
After thinking about it, I think raising the msrv is the best thing to do.
I've already done that, so you only have to rebase this onto main.

**Comment by alexkazik** [comment]
A new version with this feature is released.

**Pull request merged**
